services:
  web: &web
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - app_venv:/app/.venv
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql+asyncpg://postgres:password@postgres:5432/prompter
    depends_on:
      - redis
      - postgres
    command: ["quart", "run", "--host", "0.0.0.0", "--port", "5000"]

  worker:
    <<: *web
    ports: []
    command:
      [
        "celery",
        "-A",
        "src.create_worker.worker",
        "worker",
        "--loglevel",
        "debug",
      ]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
      - "6380:6380"

  postgres:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=prompter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  app_venv:
